// <auto-generated />
using System;
using AircraftRepair.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AircraftRepair.Migrations
{
    [DbContext(typeof(AircraftRepairDbContext))]
    [Migration("20260226124629_SeedPermissions")]
    partial class SeedPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AircraftRepair.Entities.AppUser", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int>("IdPermission")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionIdPermission")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("PermissionIdPermission");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AircraftRepair.Entities.Assignment", b =>
                {
                    b.Property<int>("IdAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAssignment"));

                    b.Property<int>("AppUserIdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdTask")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("TaskItemIdTask")
                        .HasColumnType("int");

                    b.HasKey("IdAssignment");

                    b.HasIndex("AppUserIdUser");

                    b.HasIndex("TaskItemIdTask");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("AircraftRepair.Entities.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermission"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermission");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            IdPermission = 1,
                            Code = 1,
                            Value = "Admin"
                        },
                        new
                        {
                            IdPermission = 2,
                            Code = 2,
                            Value = "User"
                        });
                });

            modelBuilder.Entity("AircraftRepair.Entities.TaskItem", b =>
                {
                    b.Property<int>("IdTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTask"));

                    b.Property<DateTime?>("DateAssignment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDelivery")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdState")
                        .HasColumnType("int");

                    b.Property<int>("TaskStateIdState")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTask");

                    b.HasIndex("TaskStateIdState");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("AircraftRepair.Entities.TaskState", b =>
                {
                    b.Property<int>("IdState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdState"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdState");

                    b.ToTable("TaskStates");

                    b.HasData(
                        new
                        {
                            IdState = 1,
                            Code = 1,
                            Value = "pending"
                        },
                        new
                        {
                            IdState = 2,
                            Code = 2,
                            Value = "inProgress"
                        },
                        new
                        {
                            IdState = 3,
                            Code = 3,
                            Value = "done"
                        });
                });

            modelBuilder.Entity("AircraftRepair.Entities.AppUser", b =>
                {
                    b.HasOne("AircraftRepair.Entities.Permission", "Permission")
                        .WithMany("AppUsers")
                        .HasForeignKey("PermissionIdPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("AircraftRepair.Entities.Assignment", b =>
                {
                    b.HasOne("AircraftRepair.Entities.AppUser", "AppUser")
                        .WithMany("Assignments")
                        .HasForeignKey("AppUserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AircraftRepair.Entities.TaskItem", "TaskItem")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskItemIdTask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("AircraftRepair.Entities.TaskItem", b =>
                {
                    b.HasOne("AircraftRepair.Entities.TaskState", "TaskState")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStateIdState")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskState");
                });

            modelBuilder.Entity("AircraftRepair.Entities.AppUser", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("AircraftRepair.Entities.Permission", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("AircraftRepair.Entities.TaskItem", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("AircraftRepair.Entities.TaskState", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
